// user
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const UPDATE_USER_AVATAR = 'UPDATE_USER_AVATAR';
export const UPDATE_USER_STATUS = 'UPDATE_USER_STATUS';
export const UPDATE_USER_COLORS = 'UPDATE_USER_COLORS';
export const UPDATE_USER_STARRED = 'UPDATE_USER_STARRED';
export const CLEAR_USER = 'CLEAR_USER';

// channel
export const SET_CURRENT_CHANNEL = 'SET_CURRENT_CHANNEL';
export const SET_CHANNEL_TOP_USERS = 'SET_CHANNEL_TOP_USERS';

// messages
export const SET_MESSAGES = 'SET_MESSAGES';
